# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      id-token: write
      contents: read 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - run: npm install

      - run: npm run build
        env:
          NODE_ENV: production
          VUE_APP_SPECKLE_ID_ARUP: ${{ secrets.VUE_APP_SPECKLE_ID_ARUP }}
          VUE_APP_SPECKLE_SECRET_ARUP: ${{ secrets.VUE_APP_SPECKLE_SECRET_ARUP }}
          VUE_APP_SPECKLE_ID_XYZ: ${{ secrets.VUE_APP_SPECKLE_ID_XYZ }}
          VUE_APP_SPECKLE_SECRET_XYZ: ${{ secrets.VUE_APP_SPECKLE_SECRET_XYZ }}
          VUE_APP_SPECKLE_NAME: ${{ secrets.VUE_APP_SPECKLE_NAME }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::387698182921:role/GitHub
          role-session-name: rolesession
          aws-region: eu-west-1

      - name: Upload files to S3
        working-directory: dist
        run: |
          aws s3 sync --delete . s3://speckleworks-hackathon-static-pages-prod

      - name: Invalidate Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ET2Q90L5T7A6B --paths /index.html 
